CREATE TABLE clientes (
	idCliente INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(50) NOT NULL,
	endereco VARCHAR(100) NOT NULL,
	email VARCHAR(60) NOT NULL,
	telefone VARCHAR(15) NOT NULL,
	host VARCHAR(50)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
