version: "3.7"

services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    hostname: "mysql"
    ports:
      - 3306:3306
    networks:
      - toshiro-net
    volumes:
      - dados-bd:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Senha123
      MYSQL_DATABASE: bd_toshiro
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == linux]
        constraints: [node.role == manager]
      resources:
        limits:
          cpus: '0.50'
          memory: 256M

  app:
    image: webdevops/php-apache:alpine-php7
    ports:
      - 8080:80
    networks:
      - toshiro-net
    working_dir: /app
    volumes:
      - ./index.php:/app/index.php
    deploy:
      mode: replicated
      replicas: 4
      placement:
        constraints: [node.platform.os == linux]
#        constraints: [node.role == worker]
      resources:
        limits:
          cpus: '0.20'
          memory: 64M
    depends_on:
      - mysql

  proxy:
    image: nginx
    ports:
      - 80:80
    networks:
      - toshiro-net
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
      resources:
        limits:
          cpus: '0.20'
          memory: 64M

volumes:
  dados-bd:
  dados-app:

networks:
  toshiro-net: