Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.define "node1" do |node1|
    node1.vm.network "public_network", ip: "192.168.15.31", bridge: "wlp4s0"
#    node1.vm.network "forwarded_port", guest: 80, host: 8080
    node1.vm.hostname = "node1"
    node1.vm.provision "shell", inline: "curl -fsSL https://get.docker.com | sh -"
    node1.vm.provision "shell", inline: "apt-get install -y nfs-server"
    node1.vm.provision "shell", inline: "echo '/var/lib/docker/volumes/ 192.168.15.32(rw,sync,subtree_check) 192.168.15.33(rw,sync,subtree_check)' > /etc/exports && exportfs -ar"
    node1.vm.provision "shell", inline: "chmod 707 /var/lib/docker/volumes/"
    node1.vm.provision "shell", inline: "echo '192.168.15.32 node2' >> /etc/hosts"
#    node1.vm.provision "shell", inline: "echo '192.168.15.33 node3' >> /etc/hosts"
    node1.vm.provision "shell", inline: "docker swarm init --advertise-addr 192.168.15.31"
    node1.vm.provision "shell", inline: "docker swarm join-token worker | tail -n 2 - > /var/lib/docker/volumes/swarm-join"
    node1.vm.synced_folder ".", "/home/vagrant", disabled: true
    node1.vm.provider "virtualbox" do |v|
      v.name = "node1"
      v.memory = 1024
      v.cpus = 1
      v.linked_clone = true
    end
  end

  config.vm.define "node2" do |node2|
    node2.vm.network "public_network", ip: "192.168.15.32", bridge: "wlp4s0"
#    node2.vm.network "forwarded_port", guest: 80, host: 8080
    node2.vm.hostname = "node2"
    node2.vm.provision "shell", inline: "curl -fsSL https://get.docker.com | sh -"
    node2.vm.provision "shell", inline: "apt-get install -y nfs-common"
    node2.vm.provision "shell", inline: "echo '192.168.15.31 node1' >> /etc/hosts"
#    node2.vm.provision "shell", inline: "echo '192.168.15.33 node3' >> /etc/hosts"
    node2.vm.provision "shell", inline: "mount -o v3 node1:/var/lib/docker/volumes/ /var/lib/docker/volumes/"
    node2.vm.provision "shell", inline: "cat /var/lib/docker/volumes/swarm-join | sh - && rm -f /var/lib/docker/volumes/swarm-join"
    node2.vm.synced_folder ".", "/home/vagrant", disabled: true
    node2.vm.provider "virtualbox" do |v|
      v.name = "node2"
      v.memory = 1024
      v.cpus = 1
      v.linked_clone = true
    end
  end
  
#    config.vm.define "node3" do |node3|
#    node3.vm.network "public_network", ip: "192.168.15.33", bridge: "wlp4s0"
##    node3.vm.network "forwarded_port", guest: 80, host: 8080
#    node3.vm.hostname = "node3"
#    node3.vm.provision "shell", inline: "curl -fsSL https://get.docker.com | sh -"
#    node3.vm.provision "shell", inline: "apt-get install -y nfs-common"
#    node3.vm.provision "shell", inline: "echo '192.168.15.31 node1' >> /etc/hosts"
#    node3.vm.provision "shell", inline: "echo '192.168.15.32 node2' >> /etc/hosts"
#    node3.vm.provision "shell", inline: "mount -o v3 node1:/var/lib/docker/volumes/ /var/lib/docker/volumes/"
#    node3.vm.provision "shell", inline: "cat /var/lib/docker/volumes/swarm-join | sh - && rm -f /var/lib/docker/volumes/swarm-join"
#    node3.vm.synced_folder ".", "/home/vagrant", disabled: true
#    node3.vm.provider "virtualbox" do |v|
#      v.name = "node3"
#      v.memory = 1024
#      v.cpus = 1
#      v.linked_clone = true
#    end
#  end
end
